### ISSUE TITLE
Validation of profile using templateId vs. meta.profile

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/CDA-ccda#1]
Need to figure out how validation will work, when CDA uses "templateId" as the unique identifier of an instance, while FHIR uses meta.profile.

**Comment by grahamegrieve** [comment]
I'll think about that. it's really about how to get the validator to pick up on the template ID to prompt validation, right?

**Comment by seanmcilvenna** [comment]
Yes, exactly. If we have a CDA instance like so:

```
<ClinicalDocument>
  <templateId root="2.16...." />
  ...
    ...
      <observation>
         <templateId root="2.16..." />
      </observation>
</ClinicalDocument>
```

How do we get the validator to recognize that it needs to use one profile for <ClinicalDocument> (with a specific templateId in it), and another profile for <observation> (with a different templateId in it).

**Comment by grahamegrieve** [comment]
I think it will be something like putting an extension on the definition of templateId specifying how it declares a profile to enforce.

**Comment by seanmcilvenna** [comment]
I like it! Something like this?:

```xml
<element id="AuthoringDevice.templateId">
    <extension url="http://hl7.org/fhir/StructureDefinition/extension-profile-identifier">
        <valueString value=".root" />
    </extension>
    <path value="AuthoringDevice.templateId"/>
    <definition value="When valued in an instance, this attribute signals the imposition of a set of template-defined constraints. The value of this attribute provides a unique identifier for the templates in question"/>
    <min value="0"/>
    <max value="*"/>
    <type>
        <code value="http://hl7.org/fhir/cda/StructureDefinition/II"/>
    </type>
</element>
```

templateId is re-defined on every main class in CDA... So, we would have to repeat it, unfortunately. But, if you establish the extension I can make sure it's added everywhere that's needed.

So in this case, this extension indicates that the identifier for the an instance of a profile is the .root property of a templateId. The StructureDefinition for the II data-type indicates that "root" is an xmlAttr representation, so your validation logic would know to look in cda:templateId/@root.

In the past, we have used templateId/@extension to represent the _version_ of the template/profile to validate with... Not sure if we can take that into account with this pattern.
