### ISSUE TITLE
Value set problems

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/CDA-ccda#2]
need to change references to vsac url:
http://hl7.org/fhir/ccda/ValueSet/1.3.6.1.4.1.12009.10.2.5
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.1.11.20.2.3
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.1.11.20.2.4
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.1.1
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.6.1
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.8.1
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.9.31
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.9.59

not found in vsac with vsac url:
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.11.20.4.1
http://hl7.org/fhir/ccda/ValueSet/2.16.840.1.113883.1.11.20.22

Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1099.10: The value set '2.16.840.1.113762.1.4.1099.10' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.1.11.20275: The value set '2.16.840.1.113883.1.11.20275' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.28: The value set '2.16.840.1.113883.11.20.9.28' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.34: The value set '2.16.840.1.113883.11.20.9.34' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.46: The value set '2.16.840.1.113883.11.20.9.46' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.56: The value set '2.16.840.1.113883.11.20.9.56' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.3221.5.2: The value set '2.16.840.1.113883.3.88.12.3221.5.2' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.3221.7.4: The value set '2.16.840.1.113883.3.88.12.3221.7.4' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.80.1: The value set '2.16.840.1.113883.3.88.12.80.1' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.80.2: The value set '2.16.840.1.113883.3.88.12.80.2' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.80.33: The value set '2.16.840.1.113883.3.88.12.80.33' is not found.
Error for URL https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.88.12.80.63: The value set '2.16.840.1.113883.3.88.12.80.63' is not found.

**Comment by grahamegrieve** [comment]
where do we want to find the source for these?
