### ISSUE TITLE
OIDs vs. URLs

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/CDA-ccda#3]
CDA implementation guides use a lot of OIDs and NO urls... need guidance on how to represent a CDA OID in FHIR. We shouldn’t just prefix the OID with a base URL because that will confuse implementers. The tooling needs to simply handle (and show the reader) an OID.

Current plan for StructureDefinition and ValueSet resources:
1. Make the ID of the resource the OID
2. Create an identifier in the StructureDefinition that has a full URN for the template (ex: urn:hl7ii:OID:DATE)
3. Create a "date" property on the StructureDefinition to hold the date/extension of the template (which is used as a version, as well).

**Comment by seanmcilvenna** [comment]
This also impacts derived profiles and how the StructureDefinition.baseDefinition looks for a profile that derives another C-CDA profile.

**Comment by grahamegrieve** [comment]
there's multiple usages for OIDs, right? The comments above seem only to apply to value set OIDs?

**Comment by seanmcilvenna** [comment]
Yes, OIDs are used in templates (profiles?), as well. Right now, I am setting the ValueSet.id and StructureDefinition.id to the OID of the valueset/profile, and using .date or .version to track the version.
